spring.application.name=phishguard-backend
virustotal.api.key=aa6ceadf08752c24ed0302f55a1cd65f454ece42bbf1f4dcf73791ec622bc2c1
gemini.api.key=AQ.Ab8RN6KCJu2wLQ0ncpnU5YOuFv84FUCbAIYa7yTRmEe9Wyxa3Q
spring.datasource.url=jdbc:mysql://localhost:3306/phishguard
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect